[package]
name = "part"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "split"
path = "src/main.rs"

[[bin]]
name = "combine"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
crc32fast = "1.3.2"
clap = "3.2.8"